NumPy Continue

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import time 
try:
    while True:
        a=np.random.randint(0,255,(50,50,3))
        plt.imshow(a)
        plt.show()
        time.sleep(0.03)
        display(clear=True)
        
except:
    print('Stopped')

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
arr=np.random.randint(1,10,(4,3,3))
print(arr)

splitted_arr=np.split(arr,2)
print(splitted_arr)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
arr=np.random.randint(0,255,(4,4,3))
print(f"Original Array\n{arr}\n Splitted Array ")
two_split_arr=np.split(arr,2)
print(two_split_arr)
'''plt.imshow(new_arr[0]) #to print first half of the splitted array
plt.show()
plt.imshow(new_arr[1]) #to print second half of the splitted array
plt.show()'''

four_split_arr=np.split(arr,4)
print(four_split_arr)

print(np.split(arr,2, axis=1))

In [ ]:
#To split the image in half
import numpy as np
import matplotlib.pyplot as plt
url='D:\\Data Science\\Summer-Training-Project\\Day_9\\20250713_154809.jpg'
arr=plt.imread(url)
punch_cat=arr.copy() #Need to make a copy first
punch_cat.shape #Check the shape of the image array first
print(arr.shape)
print(arr)

# plt.imshow(punch_cat)
plt.imshow(np.split(arr,2,axis=0)[0])
plt.imshow(np.split(arr,4,axis=1)[3])


# 1080//7 = 154
# plt.show(punch_cat[:,:154,:]) 

In [ ]:
#np.where()
import numpy as np
arr=np.random.randint(1,500,(4,4))
print(arr)
location=np.where(arr>200)
print(type(location))
display(np.where(arr>200,'High Sales','Low Sales'))
display(np.where(arr>200,'High Sales',arr))


#Clip() to handle outliers (same as upper whisker and lower whisker)
np.clip(arr,100,300) #100 is lower whisker, 300 is upper whisker

Broadcasting

In [ ]:
import numpy as np
arr_1=np.random.randint(1,10,4)
arr_2=np.random.randint(1,10,(2,4))
print(f"1D Array: \n{arr_1}")
print(f"2D Array: \n{arr_2}")
print(f"Broadcasted array:\n{arr_2+arr_1}")


1D Array: 
[4 8 2 3]
2D Array: 
[[1 9 1 4]
 [2 6 9 9]]
Broadcasted array:
[[ 5 17  3  7]
 [ 6 14 11 12]]
